services:
  db:
    image: postgis/postgis:16-3.4
    container_name: roadpulse_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-enable-postgis.sql:ro

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: roadpulse_backend
    env_file: .env
    environment:
      POSTGRES_HOST: db
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: roadpulse_frontend
    env_file: .env
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules   # <-- important
    command: [ "npm", "run", "dev", "--", "--host" ]

volumes:
  dbdata:
