# Generated by Django 5.2.6 on 2025-10-15 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp_core', '0003_appuser_reward_points_exchangeitem_rewardredemption'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('EARN', 'Earn'), ('SPEND', 'Spend'), ('ADJUST', 'Adjust')], max_length=10)),
                ('amount', models.PositiveIntegerField(help_text='Always positive; sign implied by kind')),
                ('reason', models.CharField(max_length=120)),
                ('reference', models.CharField(blank=True, help_text='Idempotency key to avoid double-charging (optional)', max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='rp_core_poi_user_id_fe914a_idx'), models.Index(fields=['user', 'reference'], name='rp_core_poi_user_id_1a34fa_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='pt_amount_gt_zero')],
            },
        ),
    ]
