# Generated by Django 5.2.7 on 2025-12-20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rp_core", "0004_pointtransaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentreport",
            name="consecutive_no_votes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="ended_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="no_votes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="required_votes",
            field=models.PositiveIntegerField(default=7, help_text="Total votes required to close the report."),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="settled_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="status",
            field=models.CharField(choices=[("OPEN", "Open"), ("CONFIRMED", "Confirmed"), ("REJECTED", "Rejected"), ("TIED", "Tied")], db_index=True, default="OPEN", max_length=20),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="total_votes",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="yes_votes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="IncidentReportVote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("choice", models.CharField(choices=[("YES", "Yes"), ("NO", "No")], max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("report", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="votes", to="rp_core.incidentreport")),
                ("voter", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="incident_report_votes", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="incidentreportvote",
            constraint=models.UniqueConstraint(fields=("report", "voter"), name="uniq_incident_vote_per_user"),
        ),
    ]

