# Generated by Django 5.2.9 on 2025-12-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp_core', '0004_pointtransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
