# Generated by Django 6.0 on 2025-12-31 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp_core', '0004_pointtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='cumulative_distance',
            field=models.FloatField(default=0.0, help_text='Total distance travelled by the user (kilometres)'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='provisional_points',
            field=models.PositiveIntegerField(default=0, help_text='Provisional points pending hazard outcomes; not spendable.'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='consecutive_no_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='ended_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='no_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='required_votes',
            field=models.PositiveIntegerField(default=7, help_text='Total votes required to close the report.'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='settled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('TIED', 'Tied')], db_index=True, default='OPEN', max_length=20),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='total_votes',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='yes_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='reward_points',
            field=models.FloatField(default=0.0, help_text='Points available for redeeming rewards.'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='IncidentProvisionalMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('REPORTER', 'Reporter'), ('VOTER', 'Voter')], max_length=20)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('settled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisional_marks', to='rp_core.incidentreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_provisional_marks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('report', 'user', 'role'), name='uniq_incident_provisional_mark')],
            },
        ),
        migrations.CreateModel(
            name='IncidentReportVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='rp_core.incidentreport')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_report_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('report', 'voter'), name='uniq_incident_vote_per_user')],
            },
        ),
    ]
