# Generated by Django 5.2.6 on 2025-12-26 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rp_core', '0005_add_cumulative_distance'),
        ('rp_core', '0005_alter_appuser_username'),
    ]

    operations = [
    ]
