# Generated by Django 5.2.9 on 2026-01-03 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp_core', '0005_appuser_cumulative_distance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ITEM_CREATED', 'Item Created'), ('ITEM_UPDATED', 'Item Updated'), ('ITEM_DEACTIVATED', 'Item Deactivated'), ('REDEEM_REQUESTED', 'Redeem Requested'), ('REDEEM_APPROVED', 'Redeem Approved'), ('REDEEM_REJECTED', 'Redeem Rejected'), ('REDEEM_CANCELLED', 'Redeem Cancelled')], max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_events_as_actor', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='rp_core.exchangeitem')),
                ('redemption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='rp_core.rewardredemption')),
                ('subject_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_events_as_subject', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
