# Generated by Django 5.2.9 on 2025-12-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp_core', '0005_appuser_cumulative_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointtransaction',
            name='expiry_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When these points expire (null means never expires)', null=True),
        ),
    ]
