# Generated by Django 5.2.6 on 2025-12-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp_core', '0006_merge_20251226_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='reward_points',
            field=models.FloatField(default=0.0, help_text='Points available for redeeming rewards.'),
        ),
    ]
