# Generated by Django 5.2.9 on 2026-01-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp_core', '0006_exchangeitem_image_saveddestination'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Reward image', null=True, upload_to='rewards/'),
        ),
    ]
