# Generated by Django 5.2.10 on 2026-01-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp_core', '0006_rewardredemption_redeemed_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='appuser',
                    name='is_admin',
                    field=models.BooleanField(default=False, help_text='Designates whether the user is an admin (legacy field).'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE rp_core_appuser "
                        "ADD COLUMN IF NOT EXISTS is_admin boolean NOT NULL DEFAULT false;"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.AddField(
            model_name='exchangeitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Reward image', null=True, upload_to='rewards/'),
        ),
    ]
