# Generated by Django 5.2.9 on 2026-01-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp_core', '0006_rewardevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeitem',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangeitem',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
