# Generated by Django 5.2.9 on 2026-01-03 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rp_core', '0007_exchangeitem_valid_from_exchangeitem_valid_until'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RewardEvent',
        ),
    ]
