# Generated by Django 5.2.9 on 2025-12-26 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rp_core', '0005_alter_appuser_username'),
        ('rp_core', '0007_incidentreport_db_defaults'),
    ]

    operations = [
    ]
