# Generated by Django 5.2.9 on 2026-01-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp_core', '0007_exchangeitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveddestination',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
