# Generated by Django 5.2.9 on 2026-01-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp_core', '0008_saveddestination_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveddestination',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
        migrations.AlterField(
            model_name='saveddestination',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=14),
        ),
    ]
