# Generated by Django 5.2.10 on 2026-01-28 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp_core', '0008_event_saveddestination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardredemption',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='rp_core.exchangeitem'),
        ),
    ]
