# Generated by Django 5.2.10 on 2026-01-28 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rp_core', '0008_event_saveddestination'),
        ('rp_core', '0009_alter_saveddestination_latitude_and_more'),
    ]

    operations = [
    ]
